CREATE TABLE IF NOT EXISTS public.taccounts
(
    initial_amount double precision NOT NULL,
    is_active boolean,
    account_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    client_id bigint NOT NULL,
    account_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    account_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT taccounts_pkey PRIMARY KEY (account_id),
    CONSTRAINT taccounts_account_number_key UNIQUE (account_number),
    CONSTRAINT taccounts_account_type_check CHECK (account_type::text = ANY (ARRAY['Corriente'::character varying, 'Ahorro'::character varying]::text[])),
    CONSTRAINT taccounts_initial_amount_check CHECK (initial_amount >= 0::double precision)
);


CREATE TABLE IF NOT EXISTS public.ttransactions
(
    amount double precision NOT NULL,
    balance double precision NOT NULL,
    account_id bigint NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    transaction_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    transaction_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ttransactions_pkey PRIMARY KEY (transaction_id),
    CONSTRAINT fko9y3bfa6ctothwt6ntniuq9t1 FOREIGN KEY (account_id)
        REFERENCES public.taccounts (account_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT ttransactions_transaction_type_check CHECK (transaction_type::text = ANY (ARRAY['Retiro'::character varying, 'Deposito'::character varying]::text[]))
);

ALTER TABLE IF EXISTS public.ttransactions
    ADD CONSTRAINT fko9y3bfa6ctothwt6ntniuq9t1 FOREIGN KEY (account_id)
    REFERENCES public.taccounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;