CREATE TABLE IF NOT EXISTS public.tclients
(
    is_active boolean NOT NULL,
    person_id bigint NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tclients_pkey PRIMARY KEY (person_id),
    CONSTRAINT fk9rptudiv7aq0wlp79fb3j0a7a FOREIGN KEY (person_id)
        REFERENCES public.tpersons (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS public.tpersons
(
    age integer,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    dni character varying(10) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(10) COLLATE pg_catalog."default" NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tpersons_pkey PRIMARY KEY (id),
    CONSTRAINT tpersons_dni_key UNIQUE (dni),
    CONSTRAINT tpersons_age_check CHECK (age <= 150 AND age >= 18),
    CONSTRAINT tpersons_gender_check CHECK (gender::text = ANY (ARRAY['F'::character varying, 'M'::character varying]::text[]))
);

ALTER TABLE IF EXISTS public.tclients
    ADD CONSTRAINT fk9rptudiv7aq0wlp79fb3j0a7a FOREIGN KEY (person_id)
    REFERENCES public.tpersons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS tclients_pkey
    ON public.tclients(person_id);